'use strict';

// file deps
var
  Type = require('./constants/Type');

var
  types = {
    append: [ Type.STRING ],
    auth: [],
    bgrewriteaof: [],
    bgsave: [],
    bitcount: [ Type.STRING ],
    bitop: [ Type.STRING ],
    bitpos: [ Type.STRING ],
    blpop: [ Type.LIST ],
    brpop: [ Type.LIST ],
    brpoplpush: [ Type.LIST ],
    client: [],
    command: [],
    config: [],
    dbsize: [],
    debug: [],
    decr: [ Type.STRING ],
    decrby: [ Type.STRING ],
    del: [ Type.HASH, Type.HYPERLOGLOG, Type.LIST, Type.SET, Type.STRING, Type.ZSET ],
    discard: [],
    dump: [ Type.HASH, Type.HYPERLOGLOG, Type.LIST, Type.SET, Type.STRING, Type.ZSET ],
    echo: [],
    eval: [],
    evalsha: [],
    exec: [],
    exists: [ Type.HASH, Type.HYPERLOGLOG, Type.LIST, Type.SET, Type.STRING, Type.ZSET ],
    expire: [ Type.HASH, Type.HYPERLOGLOG, Type.LIST, Type.SET, Type.STRING, Type.ZSET ],
    expireat: [ Type.HASH, Type.HYPERLOGLOG, Type.LIST, Type.SET, Type.STRING, Type.ZSET ],
    flushall: [],
    flushdb: [],
    get: [ Type.STRING ],
    getbit: [ Type.STRING ],
    getrange: [ Type.STRING ],
    getset: [ Type.STRING ],
    hdel: [ Type.SET ],
    hexists: [ Type.SET ],
    hget: [ Type.SET ],
    hgetall: [ Type.SET ],
    hincrby: [ Type.SET ],
    hincrbyfloat: [ Type.SET ],
    hkeys: [ Type.SET ],
    hlen: [ Type.SET ],
    hmget: [ Type.SET ],
    hmset: [ Type.SET ],
    hscan: [ Type.SET ],
    hset: [ Type.SET ],
    hsetnx: [ Type.SET ],
    hvals: [ Type.SET ],
    incr: [ Type.STRING ],
    incrby: [ Type.STRING ],
    incrbyfloat: [ Type.STRING ],
    info: [],
    keys: [],
    lastsave: [],
    latency: [],
    lindex: [ Type.LIST ],
    linsert: [ Type.LIST ],
    llen: [ Type.LIST ],
    lpop: [ Type.LIST ],
    lpush: [ Type.LIST ],
    lpushx: [ Type.LIST ],
    lrange: [ Type.LIST ],
    lrem: [ Type.LIST ],
    lset: [ Type.LIST ],
    ltrim: [ Type.LIST ],
    mget: [ Type.STRING ],
    migrate: [ Type.HASH, Type.HYPERLOGLOG, Type.LIST, Type.SET, Type.STRING, Type.ZSET ],
    monitor: [],
    move: [ Type.HASH, Type.HYPERLOGLOG, Type.LIST, Type.SET, Type.STRING, Type.ZSET ],
    mset: [ Type.STRING ],
    msetnx: [ Type.STRING ],
    multi: [],
    object: [ Type.HASH, Type.HYPERLOGLOG, Type.LIST, Type.SET, Type.STRING, Type.ZSET ],
    persist: [ Type.HASH, Type.HYPERLOGLOG, Type.LIST, Type.SET, Type.STRING, Type.ZSET ],
    pexpire: [ Type.HASH, Type.HYPERLOGLOG, Type.LIST, Type.SET, Type.STRING, Type.ZSET ],
    pexpireat: [ Type.HASH, Type.HYPERLOGLOG, Type.LIST, Type.SET, Type.STRING, Type.ZSET ],
    pfadd: [ Type.HYPERLOGLOG ],
    pfcount: [ Type.HYPERLOGLOG ],
    pfdebug: [],
    pfmerge: [ Type.HYPERLOGLOG ],
    pfselftest: [],
    ping: [],
    psetex: [ Type.STRING ],
    psubscribe: [],
    psync: [],
    pttl: [ Type.HASH, Type.HYPERLOGLOG, Type.LIST, Type.SET, Type.STRING, Type.ZSET ],
    publish: [],
    pubsub: [],
    punsubscribe: [],
    randomkey: [],
    rename: [ Type.HASH, Type.HYPERLOGLOG, Type.LIST, Type.SET, Type.STRING, Type.ZSET ],
    renamenx: [ Type.HASH, Type.HYPERLOGLOG, Type.LIST, Type.SET, Type.STRING, Type.ZSET ],
    replconf: [],
    restore: [ Type.HASH, Type.HYPERLOGLOG, Type.LIST, Type.SET, Type.STRING, Type.ZSET ],
    role: [],
    rpop: [ Type.LIST ],
    rpoplpush: [ Type.LIST ],
    rpush: [ Type.LIST ],
    rpushx: [ Type.LIST ],
    sadd: [ Type.SET ],
    save: [],
    scan: [ Type.HASH, Type.HYPERLOGLOG, Type.LIST, Type.SET, Type.STRING, Type.ZSET ],
    scard: [ Type.SET ],
    script: [],
    sdiff: [ Type.SET ],
    sdiffstore: [ Type.SET ],
    select: [],
    set: [ Type.STRING ],
    setbit: [ Type.STRING ],
    setex: [ Type.STRING ],
    setnx: [ Type.STRING ],
    setrange: [ Type.STRING ],
    shutdown: [],
    sinter: [ Type.SET ],
    sinterstore: [ Type.SET ],
    sismember: [ Type.SET ],
    slaveof: [],
    slowlog: [],
    smembers: [ Type.SET ],
    smove: [ Type.SET ],
    sort: [ Type.LIST, Type.SET, Type.ZSET ],
    spop: [ Type.SET ],
    srandmember: [ Type.SET ],
    srem: [ Type.SET ],
    sscan: [ Type.SET ],
    strlen: [ Type.STRING ],
    subscribe: [],
    substr: [],
    sunion: [ Type.SET ],
    sunionstore: [ Type.SET ],
    sync: [],
    time: [],
    ttl: [ Type.HASH, Type.HYPERLOGLOG, Type.LIST, Type.SET, Type.STRING, Type.ZSET ],
    type: [ Type.HASH, Type.HYPERLOGLOG, Type.LIST, Type.SET, Type.STRING, Type.ZSET ],
    unsubscribe: [],
    unwatch: [],
    watch: [],
    zadd: [ Type.ZSET ],
    zcard: [ Type.ZSET ],
    zcount: [ Type.ZSET ],
    zincrby: [ Type.ZSET ],
    zinterstore: [ Type.ZSET ],
    zlexcount: [ Type.ZSET ],
    zrange: [ Type.ZSET ],
    zrangebylex: [ Type.ZSET ],
    zrangebyscore: [ Type.ZSET ],
    zrank: [ Type.ZSET ],
    zrem: [ Type.ZSET ],
    zremrangebylex: [ Type.ZSET ],
    zremrangebyrank: [ Type.ZSET ],
    zremrangebyscore: [ Type.ZSET ],
    zrevrange: [ Type.ZSET ],
    zrevrangebylex: [ Type.ZSET ],
    zrevrangebyscore: [ Type.ZSET ],
    zrevrank: [ Type.ZSET ],
    zscan: [ Type.ZSET ],
    zscore: [ Type.ZSET ],
    zunionstore: [ Type.ZSET ]
  };

module.exports = types;
